### ISSUE TITLE
Modeline overlaying org-tag minibuffer

### ISSUE THREAD

**Issue by mwip** [seagle0128/doom-modeline#213] opened 2019-08-24 12:39 UTC
When I am in org-mode and want to add a tag (`C-c C-q`) the modeline overlays the org-tag minibuffer. I was able to reproduce this on multiple machines (using the same config, though).
I think the following screenshot shows the issue better than words could. I compared my setup (top) to the vanilla `emacs -q` (bottom):
![doomline-bug](https://user-images.githubusercontent.com/29728338/63637534-663d0f00-c67d-11e9-92f5-13326af0d3a9.png)

**Environment:**
 - OS: Arch Linux
 - Version 5.2.9
 - Package version 20190820.1749

**Comment by seagle0128** [comment] 2019-08-25 14:53
I don't think it's an issue of `doom-modeline`. The same issue with `powerline`, `spaceline` and `telephone-line`, etc. So I think the root cause should be in `org` itself.

BTW, there is no issue in [Centaur](https://github.com/seagle0128/.emacs.d), while in vanilla Emacs.

**Comment by mwip** [comment] 2019-09-04 16:04
@seagle0128 what makes Centaur so different, that it would alter this specific bug in org?

Notwithstanding the above, a solution to this would be to add a (few) blank lines to the tags mini-buffer. Is there any way to achieve that?

**Comment by seagle0128** [comment] 2019-09-04 17:12
Honestly I don't know the reason, but it happens. I suggest to use `counsel-org-tag`, but you can refer to `init-org.el` for details. I think it's the issue of `org`.

**Comment by seagle0128** [comment] 2019-10-26 05:48
I committed a3b6432569b57440816155bda47ce76f1169c2b9 to address this issue.

Refer to #183 .

**Closed by seagle0128** 2019-10-26 05:48 UTC

**Comment by mwip** [comment] 2019-10-26 07:35
Awesome! Thanks
