### ISSUE TITLE
[Bug] Should IRC buffers be shortened when there's enough space?

### ISSUE THREAD

**Issue by Thaodan** [seagle0128/doom-modeline#729] opened 2024-07-26 06:31 UTC
### Thank you for the bug report

- [X] I am using the latest version of `doom-modeline` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [ ] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

Before #728 circe bufers were not shortened. Now buffers are shortened all the time even when there's enough space. 

It would be better if doom-modeline would follow the settings/behavior of tracking.el

### Steps to reproduce

1. Have irc segment enabled
2. Use circe (not really relevant necessarily
3. Visit irc buffer

### Expected behavior

Shorten buffer names only when there isn't enough space

### OS

Linux

### Emacs Version

30 (gccemacs)

### Emacs Configurations

github.com/thaodan/emacs.d

**Comment by seagle0128** [comment] 2024-07-26 07:12
Please try `(add-to-list 'doom-modeline-always-visible-segments 'irc)`.

**Comment by Thaodan** [comment] 2024-07-26 20:29
Will that make the segment visible outside of IRC buffers?

**Comment by Thaodan** [comment] 2024-07-27 11:14
`doom-modeline-always-visible-segments` is `nil`. 
`doom-modeline-window-width-limit` is 85.

**Comment by seagle0128** [comment] 2024-07-27 17:58
> `doom-modeline-always-visible-segments` is `nil`. `doom-modeline-window-width-limit` is 85.

Then you should decrease `doom-modeline-window-width-limit` to shorten IRC buffer names.

**Comment by Thaodan** [comment] 2024-07-27 22:23
The problem is not that they are shortened but that they are shortened
also when threshold isn't reached.

**Comment by seagle0128** [comment] 2024-07-28 02:55
For irc buffers, it's by design. If you don't like it, please use this.

cc @seanfarley 

```elisp
(defun doom-modeline--tracking-buffers (buffers)
  "Logic to convert some irc BUFFERS to their font-awesome icon."
  (mapconcat
   (lambda (b)
     (propertize
      (funcall doom-modeline-irc-stylize b)
      'face '(:inherit (doom-modeline-unread-number doom-modeline-notification))
      'help-echo (format "IRC Notification: %s\nmouse-1: Switch to buffer" b)
      'mouse-face 'doom-modeline-highlight
      'local-map (make-mode-line-mouse-map
                  'mouse-1
                  (lambda ()
                    (interactive)
                    (when (buffer-live-p (get-buffer b))
                      (switch-to-buffer b))))))
   buffers
   (doom-modeline-vspc)))
```

**Comment by seagle0128** [comment] 2024-08-10 16:56
Updated the  solution. I am closing it.

``` emacs-lisp
(advice-add #'doom-modeline--shorten-irc :override #'identity)
```

**Comment by seagle0128** [comment] 2024-08-10 17:01
```elisp
(setq 'doom-modeline-irc-stylize #'identity)
```

**Closed** 2024-08-10 17:03 UTC
Labels: bug
