### ISSUE TITLE
Anzu segment doesn't reset after changing buffer

### ISSUE THREAD

**Issue by wedens** [seagle0128/doom-modeline#52] opened 2018-11-27 08:33 UTC
I use evil-search.  When I do a search in one buffer then switch to the other, there is still anzu modeline segment with results (index, matches count) from the previous buffer.

Steps to reproduce:
- set `(setq evil-search-module 'evil-search)`
- press `/` for search
- enter search string and press RET
- observe results in anzu segment
- change buffer
- observe the same anzu segment

doom-modeline 88a1096

**Comment by seagle0128** [comment] 2018-11-27 12:44
Hello,
I have a few questions. First I want to double confirm if you are using `evil-anzu`, since `evil-search` won't trigger `anzu` segment. The second is how to `change buffer`: switch to other window or buffer? And whether are the same buffers in different windows?

According my understanding, I tested on my env. Below is recording on Vanilla Emacs (`emacs -Q --debug-init`). No such issue which you clarify.

![emacs](https://user-images.githubusercontent.com/140797/49082605-216a8000-f285-11e8-8b58-1b29aacd112e.gif)

**Comment by wedens** [comment] 2018-11-27 13:06
> First I want to double confirm if you are using evil-anzu, since evil-search won't trigger anzu segment.

I press `/` for a search which is bound to `evil-ex-search-forward`.

> The second is how to change buffer: switch to other window or buffer? And whether are the same buffers in different windows?

Other buffer in the same window. But if I open multiple windows, I get the same segment in all modelines.

Tried with doom-modeline 58eb5c3b5500d50420daabf3933a4377a8381f60 (HEAD). Same result.

Performing a search and opening another buffer in another window:
![peek 2018-11-27 20-02](https://user-images.githubusercontent.com/697162/49083538-7e633780-f27f-11e8-889f-e7e2c89e8bdb.gif)

Opening another buffer in the same window:
![peek 2018-11-27 20-04](https://user-images.githubusercontent.com/697162/49083629-be2a1f00-f27f-11e8-8148-d99492675159.gif)

Here I just press `/` type `defun` and press `RET`.

Emacs version: 27.0.50
OS: GNU/Linux

**Comment by wedens** [comment] 2018-11-27 13:38
Btw, I can't reproduce the issue in doom-emacs which also does `(evil-select-search-module 'evil-search-module 'evil-search)`

**Comment by wedens** [comment] 2018-11-27 13:49
I've found the cause. I don't have `global-anzu-mode` enabled (I have it in my config with an (apparently failed) attempt to lazy-load it).

Please close the issue if it's expected behaviour.

**Comment by seagle0128** [comment] 2018-11-27 15:10
Good to know the issue was addressed!

Actually some hooks are loaded after loading `anzu` to reset anzu status. `anzu-mode` should be enabled before using `evil-anzu` and `evil-search`. It's as designed so close it.

**Closed by seagle0128** 2018-11-27 15:10 UTC
