### ISSUE TITLE
mu4e icon not loading in status bar

### ISSUE THREAD

**Issue by gregf** [seagle0128/doom-modeline#326] opened 2020-04-02 09:43 UTC
**Describe**
The email icon for mu4e is just loading in as a square

**Steps and Expected**

[Doom Emacs Config](https://gist.github.com/gregf/eb5e93e1ca245e81cc5f09463b42d94a)

**Environment:**
 - OS and version: FreeBSD 13-current
 - Emacs Version: 26.3
 - Configuration: Doom
 - Package version: v2.9.2

**Additional context**
![2020-04-02_05-01](https://user-images.githubusercontent.com/980/78233742-32905600-74a4-11ea-8856-12979134c8df.png)

Material Icons Loading (so i'm assuming the fonts are installed correctly?)
![2020-04-02_05-46](https://user-images.githubusercontent.com/980/78234639-70da4500-74a5-11ea-8235-364e2c23e69b.png)

[Doom Emacs issue](https://github.com/hlissner/doom-emacs/issues/2815)

** Doom Info **

```
  (version . "26.3")
  (features . "XPM JPEG TIFF GIF PNG RSVG CAIRO IMAGEMAGICK SOUND DBUS GCONF GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LCMS2")
  (build . "Apr 02, 2020")
  (buildopts "--disable-build-details --localstatedir=/var --without-gpm --with-x --enable-acl --with-cairo --with-dbus --with-gconf --with-gif --with-gnutls --with-gsettings --with-x-toolkit=gtk3 --with-jpeg --with-file-notification=kqueue --with-lcms2 --with-m17n-flt --with-imagemagick --with-mailutils --with-modules --with-sound=oss --with-libotf --with-png --with-toolkit-scroll-bars --with-rsvg --with-threads --with-tiff --with-xft --with-xim --with-xml2 --with-xpm --with-xwidgets --x-libraries=/usr/local/lib --x-includes=/usr/local/include --prefix=/usr/local --mandir=/usr/local/man --disable-silent-rules --infodir=/usr/local/share/emacs/info/ --build=amd64-portbld-freebsd13.0 'CFLAGS=-O2 -pipe -fno-strict-aliasing -march=native  -fstack-protector-strong -isystem /usr/local/include ' 'CPPFLAGS=-isystem /usr/local/include' 'LDFLAGS= -fstack-protector-strong -L/usr/local/lib '")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD c80573e5b 2020-04-01 17:31:09 -0400")
  (dir . "/usr/home/gregf/.doom.d/"))
 (system
  (type . berkeley-unix)
  (config . "amd64-portbld-freebsd13.0")
  (shell . "/usr/local/bin/zsh")
  (uname . "FreeBSD 13.0-CURRENT FreeBSD 13.0-CURRENT #0 r359473: Mon Mar 30 21:24:00 EDT 2020     root@fluffy.local:/usr/obj/usr/src/amd64.amd64/sys/GENERIC-NODEBUG  amd64")
  (path "~/.cargo/bin" "/bin" "/sbin" "/usr/sbin" "/usr/bin" "/usr/local/bin" "~/.gem/bin/" "~/dev/go/bin" "~/bin" "~/.emacs.d/bin" "/usr/local/bin" "/usr/lib/w3m" "~/.cargo/bin" "~/.cargo/bin" "/usr/local/sbin" "/usr/bin/core_perl" "/usr/local/bin" "/usr/bin" "~/.config/bspwm/panel" "~/.bin" "/usr/local/libexec/emacs/26.3/amd64-portbld-freebsd13.0"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company helm :ui deft doom doom-dashboard fill-column hl-todo indent-guides modeline nav-flash neotree ophints (popup +all +defaults) pretty-code treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors rotate-text snippets word-wrap :emacs dired electric ibuffer vc :term eshell :checkers syntax spell grammar :tools ansible debugger direnv editorconfig (eval +overlay) gist magit make pdf rgb terraform upload :lang data emacs-lisp go javascript lua markdown (org +dragndrop +hugo -capture +pandoc) python ruby rust sh web :app irc (rss +org) :config (default +bindings +smartparens))
  (packages (org-alert) (alert) (auto-sudoedit) (flycheck-yamllint) (alarm-clock) (vue-mode) (nvm) (mu4e-alert) (org-caldav))
  (unpin "n/a")
  (elpa "n/a")))
```

**Comment by seagle0128** [comment] 2020-04-02 13:55
Are you able to reproduce with vanilla Emacs? I am afraid it's an issue of doom.

**Comment by gregf** [comment] 2020-04-02 16:36
You're right this isn't a issue in vanilla emacs.

![2020-04-02_12-35](https://user-images.githubusercontent.com/980/78274627-8029b480-74de-11ea-88d5-80b58a994e0c.png)

**Comment by gregf** [comment] 2020-04-02 20:20
What I ended up having to do is move the following line from my ~/.doom.d/config.el to the bottom of the file.

(add-hook 'after-init-hook #'mu4e-alert-enable-mode-line-display)

After that it showed up and worked fine. I first tried removing it and it wouldn't show up at all without it.

@hlissner ^

**Comment by seagle0128** [comment] 2020-04-04 12:01
Closing it since it's an issue of doom.

**Closed by seagle0128** 2020-04-04 12:01 UTC
