### ISSUE TITLE
buffer-info sometimes stop showing that buffer is modified

### ISSUE THREAD

**Issue by cspk** [seagle0128/doom-modeline#184] opened 2019-06-09 18:22 UTC
**Describe**

`buffer-info` section of `doom-modeline` stops showing that buffer is modified after some time. If I modify a buffer, it still shows that it's unmodified. Then, if I save the buffer and make `C-/` (`undo-tree-undo`), it begins to show the modified state. If I save, it stops showing again. See gif:

![ezgif-5-cdba61b1b458](https://user-images.githubusercontent.com/6134003/59162450-cacee000-8b0a-11e9-8eff-5c9b8691c5fc.gif)

I haven't figured out when exactly it happens. It just appears in the middle of work.

**Steps and Expected**

1. Use emacs with doom-modeline enabled for a while.

Expected behavior: `buffer-info` always reflects actual buffer status (whether it's modified or not).

**Environment:**
 - OS: Debian
 - Version: 10 (Buster)
 - Package version: 20190606.1021

**Additional context**
I use console emacs UI.
Emacs packages installed:

```
anzu
multiple-cursors
easy-kill
xclip
fill-column-indicator
terminal-focus-reporting
git-commit
dtrt-indent
smart-tabs-mode
total-lines
helm-projectile
doom-modeline
ctags-update
helm-cscope
evil
helm
projectile
diff-hl
undo-tree
```
Evil mode is **not** activated.
My `init.el`

```lisp
(require 'package)
(let* ((no-ssl (and (memq system-type '(windows-nt ms-dos))
                    (not (gnutls-available-p))))
       (proto (if no-ssl "http" "https")))
  (when no-ssl
    (warn "\
Your version of Emacs does not support SSL connections,
which is unsafe because it allows man-in-the-middle attacks.
There are two things you can do about this warning:
1. Install an Emacs version that does support SSL and be safe.
2. Remove this warning from your init file so you won't see it again."))
  ;; Comment/uncomment these two lines to enable/disable MELPA and MELPA Stable as desired
  (add-to-list 'package-archives (cons "melpa" (concat proto "://melpa.org/packages/")) t)
  ;;(add-to-list 'package-archives (cons "melpa-stable" (concat proto "://stable.melpa.org/packages/")) t)
  (when (< emacs-major-version 24)
    ;; For important compatibility libraries like cl-lib
    (add-to-list 'package-archives (cons "gnu" (concat proto "://elpa.gnu.org/packages/")))))

;; Added by Package.el.  This must come before configurations of
;; installed packages.  Don't delete this line.  If you don't want it,
;; just comment it out by adding a semicolon to the start of the line.
;; You may delete these explanatory comments.
(package-initialize)

(unless package-archive-contents
  (package-refresh-contents))
(package-install-selected-packages)

(unless (display-graphic-p)
  (require 'terminal-focus-reporting)
  (terminal-focus-reporting-mode))

(setq custom-file (concat user-emacs-directory "/custom.el"))
(load-file custom-file)

(defun server-shutdown ()
  "Save buffers, Quit, and Shutdown (kill) server"
  (interactive)
  (save-some-buffers)
  (kill-emacs))

(defun save-current-buffer-if-needed ()
  (interactive)
  (when (and (buffer-file-name) (buffer-modified-p))
    (save-buffer)))

(add-hook 'focus-out-hook 'save-current-buffer-if-needed)
(add-hook 'focus-in-hook 'diff-hl-update)
(add-hook 'prog-mode-hook 'fci-mode); set long line ruler
(add-hook 'git-commit-mode-hook 'fci-mode)

(global-diff-hl-mode)
(global-display-line-numbers-mode)
(global-hl-line-mode)
(global-undo-tree-mode)
(global-total-lines-mode)
(global-anzu-mode); show total matches in find/replace
(global-git-commit-mode)
(dtrt-indent-global-mode); figure out file indentation
(smart-tabs-mode); indent with tabs, align with spaces
(menu-bar-mode -1)
(tool-bar-mode -1)
(scroll-bar-mode -1)
(horizontal-scroll-bar-mode -1)
(diff-hl-margin-mode); use margin for diff signs
(diff-hl-flydiff-mode); on-the-fly highlighting (without having to save file)
(column-number-mode)

(add-to-list 'default-frame-alist
             '(font . "Terminus-10"))

(setq-default global-mode-string '(:eval (format "  %dL" total-lines)))
(setq-default tab-width 4)
(setq-default c-basic-offset 4)
(setq-default auto-save-default nil)
(setq-default make-backup-files nil)
(setq-default require-final-newline t)
(setq-default projectile-switch-project-action 'helm-projectile)
(setq-default show-trailing-whitespace t)
(setq-default scroll-conservatively 101)
(setq-default electric-pair-mode t)
(setq-default echo-keystrokes 0.01)
(setq-default git-commit-summary-max-length 50)
(setq-default column-number-indicator-zero-based nil)
(setq-default fci-rule-column 80)
(setq-default create-lockfiles nil)
(setq-default org-log-done 'note)
(setq-default org-startup-indented t)

;(whole-line-or-region-global-mode t)
(doom-modeline-mode)
(helm-mode)
(projectile-mode)
(helm-projectile-on)
(line-number-mode -1)
(setq linum-format "%4d ")
(show-paren-mode)
(xclip-mode)
(global-auto-revert-mode)

(load-file (concat user-emacs-directory "keys.el"))

(defun inhibit-save-message (f &rest args)
  (let ((inhibit-message t))
    (funcall f)))

(advice-add 'save-buffer :around #'inhibit-save-message)
```

**Comment by seagle0128** [comment] 2019-06-10 05:59
Thanks for the reporting!

Unfortunately I couldn't reproduce the issue locally. Can you try with `emacs -Q`?

**Comment by cspk** [comment] 2019-06-10 08:26
> Can you try with `emacs -Q`?

I will. But for now I can say that with simply `doom-modeline` disabled (rest of `init.el` being intact) I haven't been able to face this issue—the emacs' own modeline always handles it. I might be not giving it enough time though.

**Comment by seagle0128** [comment] 2019-06-10 08:29
BTW, what's the emacs version are you using?

**Comment by cspk** [comment] 2019-06-10 08:36
> BTW, what's the emacs version are you using?

26.1 from Debian repos.

**Comment by cspk** [comment] 2019-06-11 05:48
Also I've found out that when this bug happens, if I disable `doom-modeline-mode`, the stock emacs' modeline reflects the buffer status flawlessly. Enabling `doom-modeline-mode` again does not cure the issue.

**Comment by seagle0128** [comment] 2019-06-12 05:06
The default mode-line leverages timers to refresh the status, while `doom-modeline` leverages hooks to update the status for better performance. This issue may be caused by missing hooks, errors in hooks, or some configuration issues. According to the current information, I cannot confirm which one. So please use `emacs -Q` to reproduce, so that I can reduce the scope.

**Comment by cspk** [comment] 2019-06-14 13:40
When this issue occurs, re-evaluating `(add-hook 'after-change-functions #'doom-modeline-update-buffer-file-state-icon)
` and `(add-hook 'after-change-functions #'doom-modeline-update-buffer-file-name)` helps and restores normal functionality.

**Comment by seagle0128** [comment] 2019-06-14 14:00
But `doom-modeline-update-buffer-file-state-icon` and `doom-modeline-update-buffer-file-name` have been added into `after-change-functions` while loading `doom-modeline`. I seems more like a configuration issue.

So, did you try with `emacs -Q`? When the issue occurs, can you check the value of `after-change-functions`?

**Comment by cspk** [comment] 2019-06-14 14:39
> When the issue occurs, can you check the value of `after-change-functions`?
It's following (buffer local in a cpp buffer):
`(c-after-change jit-lock-after-change diff-hl-edit total-lines-after-change-function t fci-redraw-region)`
global value is `nil`.

> So, did you try with `emacs -Q`?
Not yet. I use emacs at work every day, so it's not that convenient without the `init.el`. Maybe on the weekend.

**Comment by seagle0128** [comment] 2019-06-14 14:50
Thanks for the update.

This is from my env.
```elisp
after-change-functions is a variable defined in ‘C source code’.
Its value is
(lsp-on-change c-after-change diff-hl-edit aggressive-indent--keep-track-of-changes jit-lock-after-change flycheck-handle-change t)
Local in buffer test.cpp; global value is 
(doom-modeline-update-buffer-file-name doom-modeline-update-buffer-file-state-icon symbol-overlay-refresh)
```

Obviously, the `after-change-functions` is set to nil in your env. That's the root cause. Please check your configuration.

**Comment by cspk** [comment] 2019-06-15 11:15
> Obviously, the `after-change-functions` is set to nil in your env.

Yes, definitely so. I just wonder why it gets set to nil just occasionally and abruptly? When it works, `after-change-functions` is just like yours with the `doom` elements. Don't even know what in `init.el` could cause this.

**Comment by seagle0128** [comment] 2019-06-15 15:21
You should do some troubleshooting in your env and find the root cause.

Well, this is a quick workaround for this case, and you can try.

```elisp
(add-hook 'after-change-functions #'doom-modeline-update-buffer-file-state-icon nil t)
(add-hook 'after-change-functions #'doom-modeline-update-buffer-file-name nil t)
```

**Comment by c0001** [comment] 2019-06-26 09:03
I encountered this problem recently, I guess it's the emacs
self-protection mechanism for hook `after-change-function` as what
indicated in its docstring that:

``` text
If an unhandled error happens in running these functions,
the variable’s value remains nil.  That prevents the error
from happening repeatedly and making Emacs nonfunctional.
```

 This paragraph cite are commented in [StackExchange](https://emacs.stackexchange.com/questions/51166/after-change-functions-global-value-gets-set-to-nil-sometimes/51167) also (indeed
 that I found there after my research on this issue.)
 
 I've tried to use `unwind-protect` to wrapper functions
 `doom-modeline-update-buffer-file-state-icon`, thus it will be fixed
 up for this, @seagle0128 do you recommend this digging method? or
 does there's any other solution.

**Comment by seagle0128** [comment] 2019-06-26 09:26
@c0001 Thanks you for the details! To avoid this issue, I change the hooks to buffer-local. Please try the new release.

**Closed** 2019-06-26 09:28 UTC
Labels: bug

**Comment by c0001** [comment] 2019-06-26 11:16
The new commit's attempting was not worked for me and the importance
that it will not inject the hook any where unless the initialization
occation (the buffer of the time invoked), for instance on any buffer
loacal hook `after-change-function' are nil.

``` text
C-h v after-change-functions

<!-- emacs shows prompt  -->
after-change-functions is a variable defined in ‘C source code’.
Its value nil
```

**Comment by seagle0128** [comment] 2019-06-26 15:01
@c0001 It seems not working for all scenarios. I reverted the last commit and add `unwind-protect` to fix this.
