### ISSUE TITLE
Tall modeline on lucid Emacs

### ISSUE THREAD

**Issue by noctuid** [seagle0128/doom-modeline#271] opened 2019-11-28 01:39 UTC
**Describe**
The modeline is very tall on lucid Emacs.

**Steps and Expected**
Install Emacs with lucid toolkit instead of gtk and enable doom-modeline.

**Environment:**
 - OS: linux 5.3.13
 - Package version: 621edf5

**Additional context**
![2019 11 27_20:31:14_-_emacsbahamut](https://user-images.githubusercontent.com/4250696/69770128-cd270400-1155-11ea-8227-db0c64b2b2dd.png)

**Comment by seagle0128** [comment] 2019-11-28 07:56
Try decreasing the value of `doom-modeline-height`.

**Comment by noctuid** [comment] 2019-11-28 14:27
Setting `doom-modeline-height` has no effect.

**Comment by seagle0128** [comment] 2019-11-28 18:33
Please check the font settings. E.g. height attributes. Evaluate doom-mideline--font-height to check the actual height.

**Comment by noctuid** [comment] 2019-11-29 14:30
The actual height is 59.

**Comment by seagle0128** [comment] 2019-11-29 17:38
It's due to your font settings. The font height is big, so the mode-line is tall.

You could check `(frame-char-height)` as well for better troubleshooting.

I am closing it since it's not a bug of `doom-modeline`.

**Comment by noctuid** [comment] 2019-11-29 22:22
>  It's due to your font settings. Did you check them?

What font settings? Any idea why this would affect doom-modeline but not the normal modeline?

**Comment by seagle0128** [comment] 2019-11-30 03:57
As mentioned above, the height attribute of the font face will affect it. Look into doom-modeline--font-height.

**Comment by noctuid** [comment] 2019-11-30 23:00
Seems like a bug with lucid Emacs giving font heights. For now I'm just advising `doom-modeline--font-height` to halve it.

**Comment by seagle0128** [comment] 2019-12-02 21:07
@noctuid Are you using Emacs 27? I upgraded to the latest Emacs 27 on Ubuntu, and get 55 of `(frame-char-height)`, but it's 18 before.

**Comment by noctuid** [comment] 2019-12-03 01:16
Yeah, I compiled from master. I can report it. Did this happen for regular emacs 27 for you (I assumed it was because I switched from gtk to lucid, but I guess it was just because I updated?)?

**Comment by seagle0128** [comment] 2019-12-03 07:34
I am using this build on Mint Linux 19.2. The issue should not exists on GTK build but I didn't test with it.

![image](https://user-images.githubusercontent.com/140797/70028279-320fad80-15df-11ea-897d-1079536321c0.png)

**Comment by seagle0128** [comment] 2019-12-03 09:47
After some testing, I am thinking maybe the height in the current lucid Emacs is  correct, while others are incorrect. I don't understand the difference of the behaviors here honestly.

Anyway I submitted a patch to address this issue, but also it brings some side-effects. Please help to test.

**Comment by nsemrau** [comment] 2019-12-04 13:51
Commit 09fa73b22c277f3fe3e4b416e519e100fc479afa breaks my setup.

The usual height of the mode-line is decreased about 1/3 now and mode-lines in adjacent buffers with varying icons do not align in height anymore:

![test](https://user-images.githubusercontent.com/4363876/70147343-4bc6f880-16a4-11ea-941f-321767ca452d.png)

The buffer on the left only shows the org-mode major mode icon.

Setup:
Emacs 26.2
GTK3 build
Font: Iosevka Medium 13

```
(setq doom-modeline-buffer-modification-icon nil
      doom-modeline-buffer-encoding nil
      doom-modeline-buffer-file-name-style 'file-name
      doom-modeline-env-version nil)
```

**Comment by seagle0128** [comment] 2019-12-04 17:06
It's the side effect that I mentioned above. You need to increase `doom-modeline-height`.

The workaround is not perfect unless Emacs team fixes the issue. If we know how to check if it's lucid build, I may make the workaround better.

**Comment by seagle0128** [comment] 2019-12-04 17:35
I submitted a new patch just now. But I still don't know if it fixed all cases since the behaviors of new Emacs is indefinite.

**Comment by noctuid** [comment] 2019-12-04 20:28
You can check if Emacs as built with lucid like this `(string-match "--with-x-toolkit=lucid" system-configuration-options)`. When I have time I'll check to make sure that this doesn't happen for non-lucid Emacs 27 and will ask about it on the bug tracker.

**Comment by seagle0128** [comment] 2019-12-06 16:58
@noctuid Could you please provide the value of `system-configuration-options` in your env here?

**Comment by noctuid** [comment] 2019-12-06 18:00
Not at my computer at the moment, but that's the flag you give to build with Lucid and the only change I made when building. I haven't had a chance yet to check if this is a problem on master without Lucid.

**Comment by seagle0128** [comment] 2019-12-06 18:07
@noctuid I did testings in my local two envs. Both are building with `--with-x-toolkit=gtk3`, and the result is the issue only exists on one (Mint Linux 19.2),  while not on the other (Manjaro Linux i3).

**Comment by seagle0128** [comment] 2020-01-20 17:45
Close it due to cde0289d0152e1c5e4e0dba12934bab4ee0836ff.

**Closed by seagle0128** 2020-01-20 17:45 UTC
Labels: bug

**Comment by Tinker-S** [comment] 2022-06-26 07:33
If anyone encounters a similar problem, you can just ignore the result of doom-modeline--font-height. And set a suitable value for doom-modeline-height.
```
(advice-add 'doom-modeline--font-height :filter-return (lambda (_) 0))
(setq doom-modeline-height 30)
```
