### ISSUE TITLE
[Feature Request] align right hand side of active mode line with variable-pitch font

### ISSUE THREAD

**Issue by jaaasonSun** [seagle0128/doom-modeline#617] opened 2023-04-12 03:13 UTC
Right hand side of active modeline does not align correctly, while inactive mode line does. This is obvious when you switch between windows in a frame, right hand side jumps around and is quite distracting.

With minimal init script

``` elisp
;; straight bootstrap
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(straight-use-package 'use-package)
(setq straight-use-package-by-default t)

(use-package emacs
  :custom-face
  (variable-pitch ((nil (:family "SF Pro Text"))))
  (mode-line ((nil (:inherit variable-pitch))))
  (mode-line-inactive ((nil (:inherit variable-pitch)))))

(use-package doom-modeline
  :config (doom-modeline-mode))

(provide 'init)
;;; init.el ends here
```

<img width="1114" alt="截屏2023-04-12 10 51 32" src="https://user-images.githubusercontent.com/6558643/231336266-874252de-b6d9-4155-8305-909c87dd2cbe.png">

<img width="1115" alt="截屏2023-04-12 10 51 41" src="https://user-images.githubusercontent.com/6558643/231336287-614e07c9-253b-44ad-b47e-24529fbce9e8.png">

I am on macOS 12.4 using emacs 29.0.60 (built from emacs-plus). variable-pitch font is set to SF Pro Text but default variable pitch font also exhibits the same behavior.

Related: https://github.com/seagle0128/doom-modeline/issues/494

**Comment by sdycjsj** [comment] 2023-07-23 07:40
I also have this problem, variable-pitch or not. 
This seems to be fixed by changing the following line

https://github.com/seagle0128/doom-modeline/blob/41dff2c9d9f6968f15afe7d710111b4340bc9b0d/doom-modeline-core.el#L1091C41-L1091C41

to `(/ (string-pixel-width (propertize rhs-str 'face 'mode-line-active))`.
I do not really know why it works and have not tested it extensively.

**Comment by seagle0128** [comment] 2023-07-23 16:36
@sdycjsj Thanks for the clue. The `mode-line-active` face is introduced in 29, and I think `mode-line` face should be okay.

**Comment by sdycjsj** [comment] 2023-07-25 14:55
> @sdycjsj Thanks for the clue. The `mode-line-active` face is introduced in 29, and I think `mode-line` face should be okay.

With https://github.com/seagle0128/doom-modeline/commit/6ea0051a3b25b0fb9fc67d826f37d82884e5ffb9, if I set a mode line height (different from default) with `(set-face-attribute 'mode-line nil :height xxx)` for faces `mode-line`, `mode-line-active`, and `mode-line-inactive`, the problem still exists.

However, if the `mode-line-active` face is used in https://github.com/seagle0128/doom-modeline/commit/6ea0051a3b25b0fb9fc67d826f37d82884e5ffb9, the problem is _partially_ solved. By "partially", I mean that when the rhs contains icons, the problem is still there but very minor. 

Hopefully the above information would be useful.

**Comment by seagle0128** [comment] 2023-07-25 16:44
https://github.com/seagle0128/doom-modeline/commit/6ea0051a3b25b0fb9fc67d826f37d82884e5ffb9 was reverted. mode-line and mode-line-active faces don't work well.

**Comment by seagle0128** [comment] 2023-08-04 17:29
Please check the latest version.

**Closed by seagle0128** 2023-08-04 17:29 UTC
Labels: enhancement

**Comment by sdycjsj** [comment] 2023-08-07 01:56
I can confirm that it is solved, even with icons. 👍🎉

**Comment by jaaasonSun** [comment] 2023-08-07 09:59
Can confirm too. This works on 29.1 on ns port and Mac port
