### ISSUE TITLE
[Bug] Doom modeline does not appear as active when executing Helm-posframe session

### ISSUE THREAD

**Issue by taquangtrung** [seagle0128/doom-modeline#608] opened 2023-02-08 14:36 UTC
### Thank you for the bug report

- [X] I am using the latest version of `doom-modeline` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [ ] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

I'm using Doom Emacs with Helm and [posframe](https://github.com/tumashu/posframe) setting.

When executing a Helm session (e.g., M-x), the Helm buffer appears in a posframe, but the doom modeling always appears as inactive. Below is the screenshot when the Helm buffer is active

<img width="1280" alt="Screenshot 2023-02-08 at 10 27 59 PM" src="https://user-images.githubusercontent.com/193967/217559785-64edd871-9a06-4d3d-97c2-39658dc20fce.png">

### Steps to reproduce

- Open Emacs with Helm, posframe, and helm-posframe installed.
- Run M-x. The Helm buffer will appear, but its modeling is inactive.

### Expected behavior

When I use Helm without posframe, the modeline is displayed correctly like below. So, I'm not sure this is the issue of Doom modeline or posframe.

<img width="1280" alt="Screenshot 2023-02-08 at 10 34 23 PM" src="https://user-images.githubusercontent.com/193967/217560274-7892953c-c062-4aa8-ad29-79e50ca0e34d.png">

### OS

Linux

### Emacs Version

28

### Emacs Configurations

Doom Emacs

**Comment by seagle0128** [comment] 2023-02-09 09:10
Can you please try this snippet?

```elisp
(defun doom-modeline--get-current-window (&optional frame)
  "Get the current window but should exclude the child windows.

If FRAME is nil, it means the current frame."
  (if (and (fboundp 'frame-parent) (frame-parent frame))
      (frame-selected-window (frame-parent frame))
    (frame-selected-window frame)))
```

**Comment by taquangtrung** [comment] 2023-02-09 10:15
I wrap that snippet in this function below:

```elisp
(defun tddsg--doom-modeline--get-current-window (&optional frame)
  "Get the current window but should exclude the child windows.

If FRAME is nil, it means the current frame."
  (interactive)
  (let ((window (if (and (fboundp 'frame-parent) (frame-parent frame))
                    (frame-selected-window (frame-parent frame))
                  (frame-selected-window frame))))
    (message "Window: %s" window)))
```

And binds it to: `(global-set-key (kbd "C-c C-M-w") 'tddsg--doom-modeline--get-current-window)`

Then, it returns `Window: #<window 4 on  *Minibuf-1*>` when running on Helm buffer.

**Comment by seagle0128** [comment] 2023-02-09 11:06
No. Just eval `doom-modeline--selected-window`.

**Comment by taquangtrung** [comment] 2023-02-09 11:44
It is the same when I eval in Helm buffer: `#<window 4 on  *Minibuf-1*>`

**Comment by seagle0128** [comment] 2023-02-09 15:16
I mean checking the helm frame after evaluating the snippet.

**Comment by taquangtrung** [comment] 2023-02-09 15:31
Oh, sorry for the misunderstanding. The helm frame (posframe) is still the same, still inactive.

**Comment by seagle0128** [comment] 2023-02-09 16:07
It's as designed, since the focus in minibuffer while not helm posframe.

**Comment by seagle0128** [comment] 2023-02-09 16:07
It's as designed, since the focus in minibuffer while not helm posframe.

**Comment by taquangtrung** [comment] 2023-02-10 06:57
@seagle0128: Thanks for the explanation. After looking the doom-modeline code, I can modify the function `doom-modeline--get-current-window` to activate modeling in Helm posframe buffer (a posframe is a child frame of the current main frame)

```elisp
;; My new code
(defun doom-modeline--get-current-window (&optional frame)
    "Get the current window but should exclude the child windows.

If FRAME is nil, it means the current frame."
    (frame-selected-window frame))
```
Here is my result:

![Screenshot_2023-02-10_14-47-29](https://user-images.githubusercontent.com/193967/218023613-9da44bab-1e59-4852-9b91-ed6e4d9534a1.png)

Do you think if this modification will have some side effects?

**Comment by seagle0128** [comment] 2023-02-10 15:52
It seems doom is not using the latest `doom-modeline`. See https://github.com/seagle0128/doom-modeline/blob/master/doom-modeline-core.el#L937. 

Closing...

**Closed by seagle0128** 2023-02-10 15:52 UTC
Labels: bug

**Comment by taquangtrung** [comment] 2023-02-10 17:20
Great! I just upgraded the newest doom-modeline package in Doom Emacs and it fixes the issue nicely!
