### ISSUE TITLE
Strange artifacts on icons when using doom-modeline [Bug] 

### ISSUE THREAD

**Issue by MetalMaxMX** [seagle0128/doom-modeline#600] opened 2022-12-30 04:40 UTC
### Thank you for the bug report

- [X] I am using the latest version of `doom-modeline` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [ ] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

Similar to https://github.com/protesilaos/modus-themes/issues/58 I have an issue with the way icons are displayed. For some strange reason, I get some strange artifacts in the icons of the doom-modeline when Emacs initially appears. I have tried to actually screenshot or find a way to consistently document it but so far I haven't been able to get much progress in debugging this. Simply because the bug disappears when Emacs is unfocused or if you move other windows around (I am using Xfce on Debian 11 if that's important), and getting a screenshot is hard because once I do get the setup, it just up and vanishes :(, sorta of a Heisenbug. I could try to attempt shooting a photo if necessary though to provide further proof on the matter. Maintainer would need to zoom in and detect the colors being wrong on the icons though

Regardless, I have left here my emacs.d, just rename it to that since Github doesn't really like text files 
[emacs.zip](https://github.com/seagle0128/doom-modeline/files/10323116/emacs.zip)

### Steps to reproduce

Very simple. Start Emacs and wait until the doom-modeline appears, and then observe if the artifacts or glitchy colors on the icons are present in the scratch buffer. 

### Expected behavior

No artifacts or mix of the color background within the icons themselves. 

### OS

Linux

### Emacs Version

28 (gccemacs)

### Anything else

I am using Emacs 28.2 natively compiled through libgccjit, I have left my config around and the bug happens with any color theme around, may happen less often with dark themes but still does, the artifacts disappear once Emacs is moved around slightly or if you happen to do an M-x command immediately

**Comment by seagle0128** [comment] 2022-12-30 05:38
1. Reproduce with `emacs -Q`.
2. Provide screenshots or recordings.

**Comment by MetalMaxMX** [comment] 2022-12-30 06:21
Is difficult to actually reproduce with emacs -Q because it only appears during startup so trying to eval my config isn't able to properly reproduce the issue. However, I did manage to get a screenshot out of it through my phone because attempting to actually screenshot it, from the computer, makes the issue go away (or doing an M-x, or most anything). Here it is 
![doomlinewrongpixel](https://user-images.githubusercontent.com/62585114/210040696-3d528ef2-88e4-437c-b17f-ae69bc8ab50a.png)

(My apologies for the dodgy issues due to my camera not being very good, but I hope with this I am able to clarify that the issue stems from the icons themselves having wrong pixels in the corners or the like, attempting to switch themes only cause more strange artifacts to occur)

**Comment by seagle0128** [comment] 2022-12-30 07:04
Duplicate of #328 .

**Closed by seagle0128** 2022-12-30 07:04 UTC
Labels: bug, duplicate
