### ISSUE TITLE
evil mode indicator

### ISSUE THREAD

**Issue by gregf** [seagle0128/doom-modeline#15] opened 2018-08-10 16:03 UTC
It would be nice if the modeline would somehow indicate if you are in insert mode or normal mode when using evil. A simple color change would suffice.

**Comment by Dickby** [comment] 2018-08-10 17:41
duplicate of #8

**Comment by seagle0128** [comment] 2018-08-11 17:07
Definitely it's depleted with #8.  
Seems many people like `evil`. I will add `evil-state` to the mode-line anyway.

**Closed** 2018-08-11 17:28 UTC
Labels: enhancement

**Comment by seagle0128** [comment] 2018-08-12 06:54
Screenshots:

Normal:
![image](https://user-images.githubusercontent.com/140797/43999448-135ba3c6-9e3f-11e8-93cc-cb5d673a2d0e.png)

Insert:
![image](https://user-images.githubusercontent.com/140797/43999462-5261ac64-9e3f-11e8-8da5-26a6e8cbf04b.png)

Visual:
![image](https://user-images.githubusercontent.com/140797/43999464-5b2dd034-9e3f-11e8-80ba-0fc8af3599a3.png)

Emacs:
![image](https://user-images.githubusercontent.com/140797/43999468-6763b42c-9e3f-11e8-8f1c-f4d85cc583b8.png)

Motion:
![image](https://user-images.githubusercontent.com/140797/43999480-88548abc-9e3f-11e8-9d78-759546050a12.png)

Operator:
![image](https://user-images.githubusercontent.com/140797/43999484-9a7ea40c-9e3f-11e8-8b2b-c7c46aeece1f.png)
