### ISSUE TITLE
Buffer status in org-mode

### ISSUE THREAD

**Issue by haji-ali** [seagle0128/doom-modeline#129] opened 2019-03-03 10:19 UTC
I have the `buffer-info` segment activated in my modeline but I am experiencing a weird behaviour. 
When I open an org file (I haven't tested this with other files) then write some text, the buffer status is modified. Then if I save, the buffer status is saved.

However, if I write some text ending with a space and save, the modeline still indicates that the buffer is modified (even though `(buffer-modified-p)` is `nil`). It seems that the save hook is not called for some reason and hence the modeline is not updated.

**Comment by seagle0128** [comment] 2019-03-03 18:07
Unfortunately I couldn't reproduce it. Could you please provide more details?

**Comment by haji-ali** [comment] 2019-03-03 20:42
Hmmm.. It seems the reason might be `ws-butler` which is loaded by default in doom. Disabling that package, I don't face this problem anymore. I am not sure how to fix it though.

**Comment by hlissner** [comment] 2019-03-04 07:54
@haji-ali A simple workaround is `(setq ws-butler-keep-whitespace-before-point nil)`, which disables the virtual whitespace that ws-butler restores post-save. I may merge this into Doom proper after some testing.

**Comment by hlissner** [comment] 2019-03-04 09:22
I found the cause and submitted a PR to fix it upstream in ws-butler.

**Comment by seagle0128** [comment] 2019-03-04 09:23
Thanks for addressing this issue, @hlissner !
I am closing it since it's not an issue of `doom-modeline`.

**Closed by seagle0128** 2019-03-04 09:23 UTC
Labels: question

**Comment by hlissner** [comment] 2019-03-04 16:53
@seagle0128 It looks like evil-escape is also causing this issue. Perhaps these hooks should be added too:

```elisp
(add-hook 'evil-insert-state-exit-hook #'doom-modeline-update-buffer-file-name)
(add-hook 'evil-insert-state-exit-hook #'doom-modeline-update-buffer-file-state-icon)
```

**Comment by seagle0128** [comment] 2019-03-04 17:02
Thanks, @hlissner . I've already committed.
