### ISSUE TITLE
Projectile segment errors on a new clojure project

### ISSUE THREAD

**Issue by emacswatcher** [seagle0128/doom-modeline#55] opened 2018-12-01 01:19 UTC
If I find-file directly to ~/mymodule/project.clj, I get 

```
cl-no-applicable-method: No applicable method: project-roots, (clojure . "~/mymodule/")
```
but if I navigate to the project directory dired and select the project.clj from there it starts working.

Versions: emacs 26.1, doom-modeline 20181130

**Comment by seagle0128** [comment] 2018-12-01 15:54
I think this has been fixed in https://github.com/seagle0128/doom-modeline/pull/54. Please update and check.

**Comment by FredeEB** [comment] 2018-12-01 20:04
´C-h` says
```
     Status: Installed in ‘doom-modeline-20181130.921/’ (unsigned).
```

**Comment by seagle0128** [comment] 2018-12-02 10:47
After the investigation, I realized you didn't use `projectile` but `project` was enabled, right?
If my assumption is correct, the root cause is `project` in 26.1+. I will try to fix the error in `doom-modeline`. The new build should be available a few hours later.

**Closed** 2018-12-02 10:57 UTC
