### ISSUE TITLE
lisp error "Match data clobbered by buffer modification hooks" when updating org-mode table 

### ISSUE THREAD

**Issue by mgmgmg** [seagle0128/doom-modeline#138] opened 2019-03-07 09:03 UTC
**Describe**
The error occurs when recalculating an org-mode table with activated doom-modeline.  

**Steps and Expected**
with enabled doom-modeline-mode: recompute the following table in org-mode (C-c C-c on the #+TBLFM: line).

` org
* table

 | 1 | 3 |   |
  #+TBLFM: @1$3=$1+$2
`
**Environment:**
linux, org-mode 9.2.2 from elpa, doom-modeline 20190307.716

**Additional context**

To me, it seems, some save-matchdata statement are required...

debug-on-error gives

Debugger entered--Lisp error: (error "Match data clobbered by buffer modification hooks")
  replace-match(" 6 |" t t)
  org-table-justify-field-maybe("6")
  org-table-eval-formula(nil "$1+$2" noalign nocst nostore noanalysis)
  org-table-recalculate(t)
  funcall-interactively(org-table-recalculate t)
  call-interactively(org-table-recalculate)
  org-table-calc-current-TBLFM()
  org-ctrl-c-ctrl-c(nil)
  funcall-interactively(org-ctrl-c-ctrl-c nil)
  call-interactively(org-ctrl-c-ctrl-c nil nil)
  command-execute(org-ctrl-c-ctrl-c)

**Comment by seagle0128** [comment] 2019-03-07 10:00
I couldn't reproduce this issue. I am using Emacs 26.1 with Org mode version 9.1.9 on macOS.

I suppose the issue doesn't exist without `doom-modeline`, correct? But in the backtrace, there is no clue for `doom-modeline`. It may be related to `org 9.2.2`, I think.

**Comment by seagle0128** [comment] 2019-03-08 18:04
I am closing it since there is no update so far. Please feel free reopen if you confirm it's an issue of `doom-modeline`. Thanks!

**Closed by seagle0128** 2019-03-08 18:04 UTC
Labels: question
